"""
MO NEXUS OMEGA — fastapi_react stack generator.

Turns a ProjectSpec into real, syntactically valid source files: SQLAlchemy
models with tenant scoping and soft delete, Pydantic schemas, FastAPI routers
with auth dependencies baked in, a minimal React shell, and an OpenAPI-adjacent
description. This is the only stack in IMPLEMENTED_STACKS (see intent.py) —
claiming another stack works without a generator here is exactly the failure
the directive prohibits.

Every generated file is syntax-checked with `ast.parse` (Python) or a brace/paren
balance check (JS/TS) before it is accepted — a generator bug produces a
BUILD_FAILED result, never a file nobody can compile.
"""

from __future__ import annotations

import ast
import hashlib
import textwrap
from dataclasses import dataclass
from typing import Any

from ..catalog import FieldSpec, ModelSpec, PageSpec
from ..requirements import ProjectSpec

FIELD_TYPE_TO_SQLALCHEMY = {
    "string": "String(255)", "text": "Text", "integer": "Integer", "float": "Float",
    "boolean": "Boolean", "datetime": "DateTime", "date": "Date", "json": "Text", "enum": "String(40)",
}
FIELD_TYPE_TO_PYDANTIC = {
    "string": "str", "text": "str", "integer": "int", "float": "float",
    "boolean": "bool", "datetime": "datetime", "date": "date", "json": "dict", "enum": "str",
}


@dataclass
class GeneratedFile:
    path: str
    content: str
    language: str

    @property
    def sha256(self) -> str:
        return hashlib.sha256(self.content.encode("utf-8")).hexdigest()

    @property
    def size_bytes(self) -> int:
        return len(self.content.encode("utf-8"))


class GenerationError(Exception):
    def __init__(self, path: str, reason: str):
        super().__init__(f"{path}: {reason}")
        self.path = path
        self.reason = reason


def _pascal(name: str) -> str:
    return "".join(w.capitalize() for w in name.replace("-", "_").split("_"))


def _model_file(model: ModelSpec) -> GeneratedFile:
    lines = [
        '"""Generated by MO Universal Builder. Edit through the Builder, not by hand,',
        "or mark your change CUSTOM_CODE so round-trip generation preserves it.",
        '"""',
        "from __future__ import annotations",
        "from datetime import datetime",
        "from sqlalchemy import Boolean, Column, Date, DateTime, Float, Integer, String, Text",
        "from sqlalchemy.orm import relationship",
        "from app.database import Base",
        "",
        "",
        f"class {model.name}(Base):",
        f'    """{model.description}"""',
        "",
        f'    __tablename__ = "{model.table}"',
        "",
        "    id = Column(Integer, primary_key=True, index=True)",
        '    tenant_id = Column(String(64), nullable=False, index=True)' if model.tenant_scoped else "    # not tenant-scoped",
    ]
    for f in model.fields:
        col = FIELD_TYPE_TO_SQLALCHEMY[f.type]
        args = [col]
        if f.required:
            args.append("nullable=False")
        else:
            args.append("nullable=True")
        if f.unique:
            args.append("unique=True")
        if f.indexed:
            args.append("index=True")
        if f.default is not None:
            args.append(f"default={f.default!r}")
        lines.append(f"    {f.name} = Column({', '.join(args)})")
    lines.append("    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)")
    lines.append("    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)")
    lines.append('    is_deleted = Column(Boolean, default=False, nullable=False)   # soft delete')
    lines.append("")
    return GeneratedFile(f"app/models/{model.table}.py", "\n".join(lines) + "\n", "python")


def _schema_file(model: ModelSpec) -> GeneratedFile:
    lines = [
        '"""Generated by MO Universal Builder."""',
        "from __future__ import annotations",
        "from datetime import datetime, date",
        "from typing import Optional",
        "from pydantic import BaseModel, ConfigDict",
        "",
        "",
        f"class {model.name}Base(BaseModel):",
    ]
    for f in model.fields:
        py_type = FIELD_TYPE_TO_PYDANTIC[f.type]
        annotation = py_type if f.required else f"Optional[{py_type}]"
        default = "" if f.required else f" = {f.default!r}" if f.default is not None else " = None"
        lines.append(f"    {f.name}: {annotation}{default}")
    if not model.fields:
        lines.append("    pass")
    lines += [
        "",
        "",
        f"class {model.name}Create({model.name}Base):",
        "    pass",
        "",
        "",
        f"class {model.name}Update(BaseModel):",
    ]
    for f in model.fields:
        py_type = FIELD_TYPE_TO_PYDANTIC[f.type]
        lines.append(f"    {f.name}: Optional[{py_type}] = None")
    if not model.fields:
        lines.append("    pass")
    lines += [
        "",
        "",
        f"class {model.name}Out({model.name}Base):",
        "    model_config = ConfigDict(from_attributes=True)",
        "    id: int",
        "    created_at: datetime",
        "",
    ]
    return GeneratedFile(f"app/schemas/{model.table}.py", "\n".join(lines) + "\n", "python")


def _router_file(model: ModelSpec) -> GeneratedFile:
    var = model.table
    lines = [
        '"""Generated by MO Universal Builder.',
        "",
        "Every route resolves an authenticated, tenant-scoped RequestContext through",
        "mo_router() and filters by tenant_id — a generated app never trusts a client-",
        'supplied tenant.',
        '"""',
        "from __future__ import annotations",
        "from fastapi import Depends, HTTPException",
        "from sqlalchemy.orm import Session",
        "from app.database import get_db",
        "from app.security import RequestContext, resolve_context, secure_router",
        f"from app.models.{var} import {model.name}",
        f"from app.schemas.{var} import {model.name}Create, {model.name}Out, {model.name}Update",
        "",
        f'router = secure_router("/api/{var}", ["{model.name}"])',
        "",
        "",
        f'@router.post("", response_model={model.name}Out, status_code=201)',
        f"def create_{var}(",
        f"    payload: {model.name}Create,",
        "    ctx: RequestContext = Depends(resolve_context),",
        "    db: Session = Depends(get_db),",
        "):",
        f"    row = {model.name}(tenant_id=ctx.tenant_id, **payload.model_dump())",
        "    db.add(row)",
        "    db.commit()",
        "    db.refresh(row)",
        "    return row",
        "",
        "",
        f'@router.get("", response_model=list[{model.name}Out])',
        f"def list_{var}(",
        "    skip: int = 0, limit: int = 100,",
        "    ctx: RequestContext = Depends(resolve_context),",
        "    db: Session = Depends(get_db),",
        "):",
        f"    return (db.query({model.name})",
        f"            .filter({model.name}.tenant_id == ctx.tenant_id, {model.name}.is_deleted.is_(False))",
        "            .offset(skip).limit(limit).all())",
        "",
        "",
        f'@router.get("/{{item_id}}", response_model={model.name}Out)',
        f"def get_{var}(",
        "    item_id: int,",
        "    ctx: RequestContext = Depends(resolve_context),",
        "    db: Session = Depends(get_db),",
        "):",
        f"    row = (db.query({model.name})",
        f"           .filter({model.name}.id == item_id, {model.name}.tenant_id == ctx.tenant_id)",
        "           .first())",
        "    if row is None or row.is_deleted:",
        f'        raise HTTPException(status_code=404, detail="{model.name} not found.")',
        "    return row",
        "",
        "",
        f'@router.put("/{{item_id}}", response_model={model.name}Out)',
        f"def update_{var}(",
        f"    item_id: int, payload: {model.name}Update,",
        "    ctx: RequestContext = Depends(resolve_context),",
        "    db: Session = Depends(get_db),",
        "):",
        f"    row = (db.query({model.name})",
        f"           .filter({model.name}.id == item_id, {model.name}.tenant_id == ctx.tenant_id)",
        "           .first())",
        "    if row is None or row.is_deleted:",
        f'        raise HTTPException(status_code=404, detail="{model.name} not found.")',
        "    for field, value in payload.model_dump(exclude_unset=True).items():",
        "        setattr(row, field, value)",
        "    db.commit()",
        "    db.refresh(row)",
        "    return row",
        "",
        "",
        f'@router.delete("/{{item_id}}", status_code=200)',
        f"def delete_{var}(",
        "    item_id: int,",
        "    ctx: RequestContext = Depends(resolve_context),",
        "    db: Session = Depends(get_db),",
        "):",
        f"    row = (db.query({model.name})",
        f"           .filter({model.name}.id == item_id, {model.name}.tenant_id == ctx.tenant_id)",
        "           .first())",
        "    if row is None or row.is_deleted:",
        f'        raise HTTPException(status_code=404, detail="{model.name} not found.")',
        "    row.is_deleted = True",     # soft delete — never a hard DELETE by default
        "    db.commit()",
        f'    return {{"detail": f"{model.name} {{item_id}} deleted."}}',
        "",
    ]
    return GeneratedFile(f"app/routers/{var}.py", "\n".join(lines) + "\n", "python")


_PAGE_TEMPLATE = """/* Generated by MO Universal Builder. */
export default function {component}() {{
  return (
    <main className="mo-page mo-page--{kind}">
      <h1>{title}</h1>
{sections}
    </main>
  );
}}
"""


def _page_file(page: PageSpec) -> GeneratedFile:
    component = _pascal(page.name) + "Page"
    sections = "\n".join(f'      <section id="{s}" className="mo-section" />' for s in page.sections)
    content = _PAGE_TEMPLATE.format(component=component, kind=page.kind, title=page.title, sections=sections)
    route_path = page.route.strip("/").replace("/", "_") or "index"
    return GeneratedFile(f"frontend/src/pages/{route_path}.jsx", content, "javascript")


def _readme_file(spec: ProjectSpec) -> GeneratedFile:
    lines = [
        f"# {spec.intent.name}",
        "",
        "Generated by the MO NEXUS OMEGA Universal Builder Runtime. Every file below was",
        "produced from the project's ProjectSpec — nothing here was hand-written.",
        "",
        f"- Build mode: {spec.intent.build_mode.value}",
        f"- Target: {spec.intent.target_type.value} ({spec.intent.target_platform})",
        f"- Stack: {spec.intent.preferred_stack}",
        f"- Architecture: see `builder_architectures` for this project",
        "",
        "## Modules",
        "",
    ] + [f"- {m}" for m in spec.modules] + [
        "",
        "## Integrations requiring credentials",
        "",
    ] + [f"- `{i.provider}` ({i.capability}) — set `{i.credential_env_var}`" for i in spec.integrations] + [
        "",
        "None of the above are faked. Until the matching environment variable is set,",
        "the corresponding tool call returns CREDENTIAL_REQUIRED.",
        "",
    ]
    return GeneratedFile("README.md", "\n".join(lines) + "\n", "markdown")


def generate(spec: ProjectSpec) -> list[GeneratedFile]:
    """Produce every source file for the project. Raises GenerationError on a bad template."""
    files: list[GeneratedFile] = []
    for model in spec.models:
        files.append(_model_file(model))
        files.append(_schema_file(model))
        files.append(_router_file(model))
    for page in spec.pages:
        files.append(_page_file(page))
    files.append(_readme_file(spec))
    for f in files:
        _validate(f)
    return files


def _validate(f: GeneratedFile) -> None:
    if f.language == "python":
        try:
            ast.parse(f.content, filename=f.path)
        except SyntaxError as exc:
            raise GenerationError(f.path, f"generated Python does not parse: {exc}") from exc
    elif f.language == "javascript":
        opens = f.content.count("{")
        closes = f.content.count("}")
        if opens != closes:
            raise GenerationError(f.path, f"unbalanced braces ({opens} open vs {closes} close)")


# ─────────────────────────────────────────────────────────────────────────────
# Test generation (Instruction #3 §27)
# ─────────────────────────────────────────────────────────────────────────────

_TEST_HEADER = '''"""Generated by MO Universal Builder — do not hand-edit.

These tests run inside BUILD_SANDBOX during the build. They exercise the
generated models and schemas directly, so a generator regression fails the
build rather than shipping.
"""
import importlib
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
'''


def _test_models_file(spec: ProjectSpec) -> GeneratedFile:
    lines = [_TEST_HEADER, ""]
    lines.append("MODEL_MODULES = [")
    for m in spec.models:
        lines.append(f'    ("app.models.{m.table}", "{m.name}", "{m.table}"),')
    lines.append("]")
    lines += [
        "",
        "",
        "def test_every_model_module_imports():",
        '    """A generated model that cannot be imported is a build failure."""',
        "    for module_path, class_name, _ in MODEL_MODULES:",
        "        module = importlib.import_module(module_path)",
        "        assert hasattr(module, class_name), f'{module_path} is missing {class_name}'",
        "",
        "",
        "def test_every_model_is_tenant_scoped():",
        '    """Tenant isolation is structural: no tenant_id column means no boundary."""',
        "    for module_path, class_name, _ in MODEL_MODULES:",
        "        model = getattr(importlib.import_module(module_path), class_name)",
        "        columns = {c.name for c in model.__table__.columns}",
        "        assert 'tenant_id' in columns, f'{class_name} has no tenant_id column'",
        "        assert 'is_deleted' in columns, f'{class_name} has no soft-delete column'",
        "",
        "",
        "def test_table_names_match_the_spec():",
        "    for module_path, class_name, table in MODEL_MODULES:",
        "        model = getattr(importlib.import_module(module_path), class_name)",
        "        assert model.__tablename__ == table",
        "",
    ]
    return GeneratedFile("tests/test_models.py", "\n".join(lines) + "\n", "python")


def _test_schemas_file(spec: ProjectSpec) -> GeneratedFile:
    lines = [_TEST_HEADER, "", "import pytest", "", "SCHEMA_MODULES = ["]
    for m in spec.models:
        required = [f.name for f in m.fields if f.required]
        lines.append(f'    ("app.schemas.{m.table}", "{m.name}", {required!r}),')
    lines += [
        "]",
        "",
        "",
        "def test_every_schema_module_imports():",
        "    for module_path, name, _ in SCHEMA_MODULES:",
        "        module = importlib.import_module(module_path)",
        "        for suffix in ('Base', 'Create', 'Update', 'Out'):",
        "            assert hasattr(module, name + suffix), f'{module_path} missing {name}{suffix}'",
        "",
        "",
        "def test_create_schema_rejects_missing_required_fields():",
        '    """Input validation is a declared MUST requirement (sec.input_validation)."""',
        "    for module_path, name, required in SCHEMA_MODULES:",
        "        if not required:",
        "            continue",
        "        create = getattr(importlib.import_module(module_path), name + 'Create')",
        "        with pytest.raises(Exception):",
        "            create()",
        "",
        "",
        "def test_update_schema_allows_partial_input():",
        "    for module_path, name, _ in SCHEMA_MODULES:",
        "        update = getattr(importlib.import_module(module_path), name + 'Update')",
        "        instance = update()",
        "        assert instance is not None",
        "",
    ]
    return GeneratedFile("tests/test_schemas.py", "\n".join(lines) + "\n", "python")


def _test_security_file(spec: ProjectSpec) -> GeneratedFile:
    routes = [f"app/routers/{m.table}.py" for m in spec.models]
    lines = [
        _TEST_HEADER,
        "",
        f"ROUTER_FILES = {routes!r}",
        "",
        "",
        "def test_no_router_is_anonymous():",
        '    """Every generated router must be built through secure_router(), which is',
        "    authenticated by construction. A router that builds its own APIRouter",
        '    would bypass Zero Trust."""',
        "    root = pathlib.Path(__file__).resolve().parents[1]",
        "    for rel in ROUTER_FILES:",
        "        source = (root / rel).read_text()",
        "        assert 'secure_router(' in source, f'{rel} does not use secure_router()'",
        "        assert 'APIRouter(' not in source, f'{rel} builds a bare APIRouter'",
        "",
        "",
        "def test_every_query_filters_by_tenant():",
        '    """Tenant scope must appear in every database query in every router."""',
        "    root = pathlib.Path(__file__).resolve().parents[1]",
        "    for rel in ROUTER_FILES:",
        "        source = (root / rel).read_text()",
        "        query_count = source.count('db.query(')",
        "        tenant_filters = source.count('tenant_id == ctx.tenant_id')",
        "        assert tenant_filters >= query_count, (",
        "            f'{rel}: {query_count} queries but only {tenant_filters} tenant filters')",
        "",
        "",
        "def test_no_hard_delete_in_generated_routers():",
        '    """Destructive deletes are soft by default (Instruction #1 §11)."""',
        "    root = pathlib.Path(__file__).resolve().parents[1]",
        "    for rel in ROUTER_FILES:",
        "        source = (root / rel).read_text()",
        "        assert 'db.delete(' not in source, f'{rel} performs a hard delete'",
        "        assert 'is_deleted = True' in source, f'{rel} has no soft delete'",
        "",
    ]
    return GeneratedFile("tests/test_security.py", "\n".join(lines) + "\n", "python")


def generate_tests(spec: ProjectSpec) -> list[GeneratedFile]:
    """Produce the generated project's own test suite."""
    if not spec.models:
        return []
    files = [_test_models_file(spec), _test_schemas_file(spec),
             _test_security_file(spec), _test_app_file(spec)]
    for f in files:
        _validate(f)
    return files


# ─────────────────────────────────────────────────────────────────────────────
# Runtime scaffold — makes the generated project standalone and runnable
# (Instruction #3 §20 "generated apps inherit secure auth templates",
#  §21 tenant isolation, §29 observability hooks)
# ─────────────────────────────────────────────────────────────────────────────

_DATABASE_PY = '''"""Generated by MO Universal Builder — database engine and session."""
from __future__ import annotations

import os

from sqlalchemy import create_engine
from sqlalchemy.orm import declarative_base, sessionmaker

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./app.db")
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)

engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {},
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
'''

_SECURITY_PY = '''"""Generated by MO Universal Builder — the secure auth template.

Mirrors the MO Zero Trust model in a standalone application:

  * `secure_router()` builds an APIRouter whose every route already depends on
    an authenticated, tenant-resolved context. A new route is protected because
    of how the router was constructed, not because the author remembered.
  * The tenant comes from the verified token, never from the request body or a
    header a client controls.
  * No secret has a literal default. SECRET_KEY must be set or the app refuses
    to start, so a deployment can never run on a placeholder key.
"""
from __future__ import annotations

import os
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Request, status
from fastapi.security import OAuth2PasswordBearer
from jose import JWTError, jwt

ALGORITHM = "HS256"
ACCESS_TOKEN_MINUTES = int(os.getenv("ACCESS_TOKEN_MINUTES", "30"))

SECRET_KEY = os.getenv("SECRET_KEY", "")
if not SECRET_KEY:
    raise RuntimeError(
        "SECRET_KEY is not set. Generate one with `python -c \\'import secrets;"
        "print(secrets.token_urlsafe(48))\\'` and set it in the environment. "
        "This application will not start on a placeholder key."
    )

oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/auth/login", auto_error=False)


@dataclass(frozen=True)
class RequestContext:
    """Identity and tenant for one request."""

    tenant_id: str
    actor_id: str
    role: str = "staff"
    scopes: frozenset = field(default_factory=frozenset)

    def require_role(self, *roles: str) -> None:
        if self.role not in roles:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail=f"This action requires one of: {', '.join(roles)}.",
            )


def create_access_token(*, subject: str, tenant_id: str, role: str = "staff") -> str:
    payload = {
        "sub": subject,
        "tenant": tenant_id,
        "role": role,
        "exp": datetime.utcnow() + timedelta(minutes=ACCESS_TOKEN_MINUTES),
    }
    return jwt.encode(payload, SECRET_KEY, algorithm=ALGORITHM)


def resolve_context(
    request: Request,
    token: Optional[str] = Depends(oauth2_scheme),
) -> RequestContext:
    """Authenticate and derive the tenant. Tenant is never client-supplied."""
    if not token:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication required.",
            headers={"WWW-Authenticate": "Bearer"},
        )
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
    except JWTError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Token is invalid or expired.",
            headers={"WWW-Authenticate": "Bearer"},
        )
    tenant_id = payload.get("tenant")
    subject = payload.get("sub")
    if not tenant_id or not subject:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Token is missing claims.")
    return RequestContext(
        tenant_id=tenant_id,
        actor_id=str(subject),
        role=payload.get("role", "staff"),
        scopes=frozenset(payload.get("scopes") or []),
    )


def secure_router(prefix: str, tags: list) -> APIRouter:
    """An APIRouter that is authenticated by construction."""
    return APIRouter(
        prefix=prefix,
        tags=tags,
        dependencies=[Depends(resolve_context)],
        responses={401: {"description": "Authentication required"},
                   403: {"description": "Forbidden"}},
    )
'''

_OBSERVABILITY_PY = '''"""Generated by MO Universal Builder — structured logging and request ids."""
from __future__ import annotations

import json
import logging
import time
import uuid

from starlette.middleware.base import BaseHTTPMiddleware

logger = logging.getLogger("app")


class JsonFormatter(logging.Formatter):
    def format(self, record: logging.LogRecord) -> str:
        payload = {
            "ts": self.formatTime(record),
            "level": record.levelname,
            "logger": record.name,
            "message": record.getMessage(),
        }
        for key in ("request_id", "method", "path", "status_code", "duration_ms"):
            if hasattr(record, key):
                payload[key] = getattr(record, key)
        return json.dumps(payload)


def configure_logging() -> None:
    handler = logging.StreamHandler()
    handler.setFormatter(JsonFormatter())
    root = logging.getLogger()
    root.handlers = [handler]
    root.setLevel(logging.INFO)


class RequestLogMiddleware(BaseHTTPMiddleware):
    """Attaches a correlation id to every request and logs the outcome."""

    async def dispatch(self, request, call_next):
        request_id = request.headers.get("x-request-id") or uuid.uuid4().hex
        started = time.perf_counter()
        response = await call_next(request)
        duration_ms = int((time.perf_counter() - started) * 1000)
        logger.info(
            "request complete",
            extra={
                "request_id": request_id,
                "method": request.method,
                "path": request.url.path,
                "status_code": response.status_code,
                "duration_ms": duration_ms,
            },
        )
        response.headers["x-request-id"] = request_id
        return response
'''


def _main_file(spec: ProjectSpec) -> GeneratedFile:
    router_imports = [f"from app.routers.{m.table} import router as {m.table}_router"
                      for m in spec.models]
    router_mounts = [f"app.include_router({m.table}_router)" for m in spec.models]
    lines = [
        f'"""Generated by MO Universal Builder — {spec.intent.name} entry point."""',
        "from __future__ import annotations",
        "",
        "from fastapi import FastAPI",
        "",
        "from app.database import Base, engine",
        "from app.observability import RequestLogMiddleware, configure_logging",
        *router_imports,
        "",
        "configure_logging()",
        "",
        "app = FastAPI(",
        f'    title="{spec.intent.name}",',
        '    version="1.0.0",',
        ")",
        "app.add_middleware(RequestLogMiddleware)",
        "",
        *router_mounts,
        "",
        "",
        '@app.get("/health", tags=["ops"])',
        "def health():",
        '    """Liveness probe (requirement ops.health)."""',
        '    return {"status": "ok"}',
        "",
        "",
        '@app.get("/ready", tags=["ops"])',
        "def ready():",
        '    """Readiness probe — reports the database honestly rather than always ok."""',
        "    from sqlalchemy import text",
        "    try:",
        "        with engine.connect() as connection:",
        '            connection.execute(text("SELECT 1"))',
        "    except Exception as exc:",
        '        return {"status": "degraded", "database": f"{type(exc).__name__}: {exc}"}',
        '    return {"status": "ready", "database": "ok"}',
        "",
    ]
    return GeneratedFile("app/main.py", "\n".join(lines) + "\n", "python")


def _requirements_file() -> GeneratedFile:
    content = "\n".join([
        "# Generated by MO Universal Builder. Versions are pinned to a compatible",
        "# minimum; run `pip-compile` to produce a fully pinned lockfile before deploying.",
        "fastapi>=0.115.0",
        "uvicorn[standard]>=0.30.1",
        "sqlalchemy>=2.0.30",
        "pydantic>=2.10.0",
        "python-jose[cryptography]>=3.3.0",
        "python-multipart>=0.0.9",
        "psycopg2-binary>=2.9.9",
        "",
        "# dev",
        "pytest>=8.2.2",
        "",
    ])
    return GeneratedFile("requirements.txt", content, "text")


def _env_example_file(spec: ProjectSpec) -> GeneratedFile:
    lines = [
        "# Generated by MO Universal Builder.",
        "# No value here is a working default — every one must be set deliberately.",
        "",
        "# Required. The app refuses to start without it.",
        "SECRET_KEY=",
        "",
        "DATABASE_URL=sqlite:///./app.db",
        "ACCESS_TOKEN_MINUTES=30",
    ]
    if spec.integrations:
        lines += ["", "# Integrations. Until each is set, the matching capability",
                  "# returns CREDENTIAL_REQUIRED rather than pretending to work."]
        for i in spec.integrations:
            lines.append(f"{i.credential_env_var}=          # {i.provider}: {i.capability}")
    return GeneratedFile(".env.example", "\n".join(lines) + "\n", "text")


def _gitignore_file() -> GeneratedFile:
    content = "\n".join([
        "__pycache__/", "*.py[cod]", ".venv/", "venv/",
        ".env", "*.db", ".pytest_cache/", "dist/", "node_modules/", "",
    ])
    return GeneratedFile(".gitignore", content, "text")


def _package_init_files(spec: ProjectSpec) -> list[GeneratedFile]:
    docs = {
        "app/__init__.py": "Generated application package.",
        "app/models/__init__.py": "Generated SQLAlchemy models.",
        "app/schemas/__init__.py": "Generated Pydantic schemas.",
        "app/routers/__init__.py": "Generated FastAPI routers.",
    }
    return [GeneratedFile(path, f'"""{doc}"""\n', "python") for path, doc in docs.items()]


def generate_runtime(spec: ProjectSpec) -> list[GeneratedFile]:
    """The scaffold that makes generated source a standalone, runnable project."""
    files = [
        GeneratedFile("app/database.py", _DATABASE_PY, "python"),
        GeneratedFile("app/security.py", _SECURITY_PY, "python"),
        GeneratedFile("app/observability.py", _OBSERVABILITY_PY, "python"),
        _main_file(spec),
        _requirements_file(),
        _env_example_file(spec),
        _gitignore_file(),
        *_package_init_files(spec),
    ]
    for f in files:
        _validate(f)
    return files


def _test_app_file(spec: ProjectSpec) -> GeneratedFile:
    """Smoke test: the app actually boots and its ops endpoints respond."""
    lines = [
        _TEST_HEADER,
        "",
        "import os",
        "",
        "import pytest",
        "",
        "",
        "def test_app_boots_and_health_responds():",
        '    """The generated FastAPI app imports, mounts its routers and serves /health."""',
        "    from fastapi.testclient import TestClient",
        "",
        "    from app.main import app",
        "",
        "    client = TestClient(app)",
        '    response = client.get("/health")',
        "    assert response.status_code == 200",
        '    assert response.json()["status"] == "ok"',
        "",
        "",
        "def test_readiness_reports_database_state_truthfully():",
        "    from fastapi.testclient import TestClient",
        "",
        "    from app.main import app",
        "",
        "    client = TestClient(app)",
        '    body = client.get("/ready").json()',
        '    assert body["status"] in ("ready", "degraded")',
        '    assert "database" in body',
        "",
        "",
        "def test_protected_routes_reject_anonymous_requests():",
        '    """Zero Trust by construction: no token, no access."""',
        "    from fastapi.testclient import TestClient",
        "",
        "    from app.main import app",
        "",
        "    client = TestClient(app)",
        "",
        "    def walk(routes):",
        "        # FastAPI nests included routers, so a flat scan of app.routes",
        "        # misses every mounted route. Recurse.",
        "        for route in routes:",
        '            path = getattr(route, "path", None)',
        "            if path:",
        "                yield path",
        '            sub = getattr(route, "routes", None)',
        "            if sub is None:",
        '                original = getattr(route, "original_router", None)',
        '                sub = getattr(original, "routes", None) if original else None',
        "            if sub:",
        "                yield from walk(sub)",
        "",
        '    protected = sorted({p for p in walk(app.routes) if p.startswith("/api/")})',
        "    assert protected, 'no /api/ routes were mounted'",
        "    for path in protected:",
        '        if "{" in path:',
        "            continue",
        "        assert client.get(path).status_code == 401, f'{path} allowed an anonymous request'",
        "",
        "",
        "def test_app_refuses_to_start_without_a_secret_key():",
        '    """sec.no_hardcoded_secrets: there is no usable placeholder key."""',
        "    import pathlib",
        "",
        "    source = (pathlib.Path(__file__).resolve().parents[1] / 'app' / 'security.py').read_text()",
        "    assert 'SECRET_KEY = os.getenv(\"SECRET_KEY\", \"\")' in source",
        "    assert 'raise RuntimeError' in source",
        "",
    ]
    return GeneratedFile("tests/test_app.py", "\n".join(lines) + "\n", "python")
