"""
MO NEXUS OMEGA — Source export (Instruction #3 §32).

Users get their actual source back. No visual-builder lock-in: the exported
archive is a complete, runnable project directory, identical to what the build
sandbox compiled and tested.
"""

from __future__ import annotations

import io
import json
import zipfile
from datetime import datetime
from typing import Any

from sqlalchemy.orm import Session

from ..context import RequestContext
from ..db import BuilderFile, BuilderProject
from ..errors import MoResult, ResultState


def export_zip(db: Session, ctx: RequestContext, project: BuilderProject) -> MoResult:
    """Build a ZIP of the project's current version, in memory."""
    ctx.require_same_tenant(project.tenant_id, f"Project {project.id}")

    files = (
        db.query(BuilderFile)
        .filter(BuilderFile.project_id == project.id,
                BuilderFile.version == project.current_version)
        .order_by(BuilderFile.path)
        .all()
    )
    if not files:
        return MoResult(
            ResultState.BLOCKED,
            f"Project '{project.name}' has no generated files at version "
            f"{project.current_version}. Generate before exporting.",
        )

    buffer = io.BytesIO()
    root = project.slug or "mo-project"
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        for f in files:
            archive.writestr(f"{root}/{f.path}", f.content)
        archive.writestr(f"{root}/MO_BUILD_MANIFEST.json", json.dumps({
            "project_id": project.id,
            "name": project.name,
            "version": project.current_version,
            "stack": project.preferred_stack,
            "build_mode": project.build_mode,
            "target_type": project.target_type,
            "exported_at": datetime.utcnow().isoformat() + "Z",
            "file_count": len(files),
            "files": [{"path": f.path, "sha256": f.sha256, "bytes": f.size_bytes} for f in files],
            "note": "Generated by the MO NEXUS OMEGA Universal Builder Runtime. "
                    "This is the complete source — the project is not locked to the visual builder.",
        }, indent=2))

    data = buffer.getvalue()
    return MoResult.ok(
        {"filename": f"{root}-v{project.current_version}.zip", "size_bytes": len(data)},
        archive=data, file_count=len(files),
    )


def export_manifest(db: Session, ctx: RequestContext, project: BuilderProject) -> dict[str, Any]:
    """A listing of the project's files without transferring their contents."""
    ctx.require_same_tenant(project.tenant_id, f"Project {project.id}")
    files = (
        db.query(BuilderFile)
        .filter(BuilderFile.project_id == project.id,
                BuilderFile.version == project.current_version)
        .order_by(BuilderFile.path).all()
    )
    return {
        "project_id": project.id, "version": project.current_version,
        "file_count": len(files),
        "files": [
            {"path": f.path, "language": f.language, "bytes": f.size_bytes,
             "sha256": f.sha256, "is_custom_code": f.is_custom_code}
            for f in files
        ],
    }
