"""baseline legacy ez-nexus schema

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-08-26 09:15:30.400359
"""
from alembic import op
import sqlalchemy as sa


revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_alerts_id'), ['id'], unique=False)

    op.create_table('agent_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('output_data', sa.Text(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_tasks_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_tasks_id'), ['id'], unique=False)

    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('staff_email', sa.String(length=200), nullable=True),
    sa.Column('twilio_phone_number', sa.String(length=30), nullable=True),
    sa.Column('ai_greeting', sa.Text(), nullable=True),
    sa.Column('require_approval', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_businesses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_name'), ['name'], unique=False)

    op.create_table('dropship_directory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('platform_type', sa.String(length=80), nullable=False),
    sa.Column('categories', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('min_order_usd', sa.Float(), nullable=True),
    sa.Column('shipping_days_usa', sa.Integer(), nullable=True),
    sa.Column('shipping_days_intl', sa.Integer(), nullable=True),
    sa.Column('has_usa_warehouse', sa.Boolean(), nullable=True),
    sa.Column('dropship_ready', sa.Boolean(), nullable=True),
    sa.Column('api_integration', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dropship_directory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dropship_directory_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dropship_directory_name'), ['name'], unique=False)

    op.create_table('supplier_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('supplier_email', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('hcpcs_code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_products_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_products_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=300), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('agent_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('spec_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_definitions_id'), ['id'], unique=False)

    op.create_table('agent_queues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('queue_type', sa.String(length=80), nullable=True),
    sa.Column('max_wait_secs', sa.Integer(), nullable=True),
    sa.Column('greeting_message', sa.Text(), nullable=True),
    sa.Column('agents_assigned', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_queues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_queues_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_queues_id'), ['id'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('client_email', sa.String(length=200), nullable=True),
    sa.Column('client_phone', sa.String(length=30), nullable=True),
    sa.Column('service', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('call_summary', sa.Text(), nullable=True),
    sa.Column('triage_result', sa.String(length=50), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_mins', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=180), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=True),
    sa.Column('entity_id', sa.String(length=120), nullable=True),
    sa.Column('before_data', sa.Text(), nullable=True),
    sa.Column('after_data', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('campaign_type', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('ai_generated_body', sa.Text(), nullable=True),
    sa.Column('target_segment', sa.String(length=200), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('open_count', sa.Integer(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('conversion_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_name'), ['name'], unique=False)

    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('linkedin_url', sa.String(length=300), nullable=True),
    sa.Column('resume_path', sa.Text(), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('education', sa.String(length=300), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_id'), ['id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('preferred_language', sa.String(length=20), nullable=True),
    sa.Column('consent_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_id'), ['id'], unique=False)

    op.create_table('ecom_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('marketplace', sa.String(length=120), nullable=True),
    sa.Column('demand_score', sa.Integer(), nullable=True),
    sa.Column('competition_score', sa.Integer(), nullable=True),
    sa.Column('profit_score', sa.Integer(), nullable=True),
    sa.Column('supplier_score', sa.Integer(), nullable=True),
    sa.Column('trend_score', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('ai_recommendation', sa.Text(), nullable=True),
    sa.Column('supplier_name', sa.String(length=200), nullable=True),
    sa.Column('supplier_country', sa.String(length=100), nullable=True),
    sa.Column('supplier_cost', sa.Float(), nullable=True),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('estimated_profit', sa.Float(), nullable=True),
    sa.Column('estimated_monthly_sales', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ecom_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ecom_products_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ecom_products_id'), ['id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('client_email', sa.String(length=200), nullable=True),
    sa.Column('client_phone', sa.String(length=30), nullable=True),
    sa.Column('client_address', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=True)

    op.create_table('ivr_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('greeting_text', sa.Text(), nullable=True),
    sa.Column('menu_options', sa.Text(), nullable=True),
    sa.Column('fallback_action', sa.String(length=80), nullable=True),
    sa.Column('ai_enabled', sa.Boolean(), nullable=True),
    sa.Column('ai_voice', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ivr_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ivr_configs_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ivr_configs_id'), ['id'], unique=False)

    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('job_type', sa.String(length=80), nullable=True),
    sa.Column('remote_option', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('posted_boards', sa.String(length=300), nullable=True),
    sa.Column('ai_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_postings_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_title'), ['title'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ai_notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_id'), ['id'], unique=False)

    op.create_table('marketing_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('form_type', sa.String(length=80), nullable=True),
    sa.Column('fields_json', sa.Text(), nullable=True),
    sa.Column('thank_you_message', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('submission_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketing_forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketing_forms_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketing_forms_id'), ['id'], unique=False)

    op.create_table('master_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('module', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('auto_fix_available', sa.Boolean(), nullable=True),
    sa.Column('admin_approved', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('master_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_recommendations_id'), ['id'], unique=False)

    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.String(length=40), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact', sa.String(length=255), nullable=True),
    sa.Column('preferred_language', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_id'), ['id'], unique=False)

    op.create_table('pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('stages', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipelines_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipelines_id'), ['id'], unique=False)

    op.create_table('smartboss_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('insight_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=40), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('smartboss_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smartboss_insights_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_smartboss_insights_id'), ['id'], unique=False)

    op.create_table('webhook_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('events', sa.String(length=300), nullable=True),
    sa.Column('secret_key', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fail_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_configs_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_configs_id'), ['id'], unique=False)

    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_type', sa.String(length=80), nullable=False),
    sa.Column('trigger_config', sa.Text(), nullable=True),
    sa.Column('steps', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflows_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_name'), ['name'], unique=False)

    op.create_table('approval_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    with op.batch_alter_table('approval_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_tokens_token'), ['token'], unique=True)

    op.create_table('call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('call_sid', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('caller_phone', sa.String(length=30), nullable=True),
    sa.Column('called_phone', sa.String(length=30), nullable=True),
    sa.Column('duration_secs', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_logs_call_sid'), ['call_sid'], unique=True)
        batch_op.create_index(batch_op.f('ix_call_logs_id'), ['id'], unique=False)

    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('stage', sa.String(length=120), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('expected_close', sa.String(length=40), nullable=True),
    sa.Column('assigned_to', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deals_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_id'), ['id'], unique=False)

    op.create_table('ecom_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('marketplace', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('bullets', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('ad_headline', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['ecom_products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ecom_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ecom_listings_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ecom_listings_id'), ['id'], unique=False)

    op.create_table('ecom_suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('cost_per_unit', sa.Float(), nullable=True),
    sa.Column('moq', sa.Integer(), nullable=True),
    sa.Column('shipping_days', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('shipping_type', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['ecom_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ecom_suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ecom_suppliers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ecom_suppliers_product_id'), ['product_id'], unique=False)

    op.create_table('equipment_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('equipment_type', sa.String(length=180), nullable=False),
    sa.Column('diagnosis_or_reason', sa.Text(), nullable=True),
    sa.Column('prescribing_provider', sa.String(length=255), nullable=True),
    sa.Column('insurance_required', sa.Boolean(), nullable=True),
    sa.Column('prior_auth_required', sa.Boolean(), nullable=True),
    sa.Column('hcpcs_codes', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_requests_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_requests_id'), ['id'], unique=False)

    op.create_table('form_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_id'], ['marketing_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_submissions_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_form_submissions_id'), ['id'], unique=False)

    op.create_table('insurance_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('payer_name', sa.String(length=255), nullable=True),
    sa.Column('plan_type', sa.String(length=100), nullable=True),
    sa.Column('member_id', sa.String(length=120), nullable=True),
    sa.Column('group_number', sa.String(length=120), nullable=True),
    sa.Column('policy_holder', sa.String(length=255), nullable=True),
    sa.Column('relationship_to_patient', sa.String(length=80), nullable=True),
    sa.Column('phone_number', sa.String(length=40), nullable=True),
    sa.Column('eligibility_status', sa.String(length=80), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insurance_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insurance_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_insurance_profiles_patient_id'), ['patient_id'], unique=False)

    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=80), nullable=True),
    sa.Column('ai_match_score', sa.Float(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('recruiter_notes', sa.Text(), nullable=True),
    sa.Column('interview_date', sa.String(length=40), nullable=True),
    sa.Column('offer_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_applications_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_applications_id'), ['id'], unique=False)

    op.create_table('patient_intakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('insurance_name', sa.String(length=200), nullable=True),
    sa.Column('insurance_member_id', sa.String(length=100), nullable=True),
    sa.Column('insurance_group_no', sa.String(length=100), nullable=True),
    sa.Column('secondary_insurance', sa.String(length=200), nullable=True),
    sa.Column('diagnosis_codes', sa.String(length=300), nullable=True),
    sa.Column('equipment_needed', sa.String(length=300), nullable=True),
    sa.Column('prescribing_doctor', sa.String(length=200), nullable=True),
    sa.Column('npi_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('ai_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id')
    )
    with op.batch_alter_table('patient_intakes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_intakes_id'), ['id'], unique=False)

    op.create_table('phone_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('number_type', sa.String(length=40), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('purpose', sa.String(length=120), nullable=True),
    sa.Column('ivr_config_id', sa.Integer(), nullable=True),
    sa.Column('monthly_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ivr_config_id'], ['ivr_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phone_numbers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phone_numbers_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_phone_numbers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_phone_numbers_number'), ['number'], unique=False)

    op.create_table('uploaded_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.String(length=80), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('file_size_kb', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uploaded_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploaded_documents_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_documents_id'), ['id'], unique=False)

    op.create_table('workflow_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('trigger_data', sa.Text(), nullable=True),
    sa.Column('steps_completed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_executions_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_executions_id'), ['id'], unique=False)

    op.create_table('bookkeeping_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('entry_type', sa.String(length=80), nullable=True),
    sa.Column('vendor_or_customer', sa.String(length=255), nullable=True),
    sa.Column('transaction_date', sa.String(length=40), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('tax_flag', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('admin_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['uploaded_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookkeeping_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookkeeping_entries_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookkeeping_entries_id'), ['id'], unique=False)

    op.create_table('call_tracking_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('phone_number_id', sa.Integer(), nullable=True),
    sa.Column('campaign_name', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('medium', sa.String(length=120), nullable=True),
    sa.Column('utm_campaign', sa.String(length=200), nullable=True),
    sa.Column('total_calls', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_tracking_numbers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_tracking_numbers_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_tracking_numbers_id'), ['id'], unique=False)

    op.create_table('data_entry_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('extracted_fields', sa.Text(), nullable=True),
    sa.Column('missing_fields', sa.Text(), nullable=True),
    sa.Column('validation_errors', sa.Text(), nullable=True),
    sa.Column('commander_recommendations', sa.Text(), nullable=True),
    sa.Column('admin_approved', sa.Boolean(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('created_by_agent', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['uploaded_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_entry_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_entry_jobs_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_entry_jobs_id'), ['id'], unique=False)

    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('quote_number', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('client_email', sa.String(length=200), nullable=True),
    sa.Column('line_items', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('valid_until', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotes_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotes_quote_number'), ['quote_number'], unique=False)

    op.create_table('call_tracking_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_number_id', sa.Integer(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('caller_phone', sa.String(length=40), nullable=True),
    sa.Column('call_duration_secs', sa.Integer(), nullable=True),
    sa.Column('is_conversion', sa.Boolean(), nullable=True),
    sa.Column('sentiment', sa.String(length=40), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('revenue_attributed', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tracking_number_id'], ['call_tracking_numbers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_tracking_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_tracking_events_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_tracking_events_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_tracking_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_tracking_events_id'))
        batch_op.drop_index(batch_op.f('ix_call_tracking_events_business_id'))

    op.drop_table('call_tracking_events')
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotes_quote_number'))
        batch_op.drop_index(batch_op.f('ix_quotes_id'))
        batch_op.drop_index(batch_op.f('ix_quotes_business_id'))

    op.drop_table('quotes')
    with op.batch_alter_table('data_entry_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_entry_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_data_entry_jobs_business_id'))

    op.drop_table('data_entry_jobs')
    with op.batch_alter_table('call_tracking_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_tracking_numbers_id'))
        batch_op.drop_index(batch_op.f('ix_call_tracking_numbers_business_id'))

    op.drop_table('call_tracking_numbers')
    with op.batch_alter_table('bookkeeping_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookkeeping_entries_id'))
        batch_op.drop_index(batch_op.f('ix_bookkeeping_entries_business_id'))

    op.drop_table('bookkeeping_entries')
    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_executions_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_executions_business_id'))

    op.drop_table('workflow_executions')
    with op.batch_alter_table('uploaded_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploaded_documents_id'))
        batch_op.drop_index(batch_op.f('ix_uploaded_documents_business_id'))

    op.drop_table('uploaded_documents')
    with op.batch_alter_table('phone_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phone_numbers_number'))
        batch_op.drop_index(batch_op.f('ix_phone_numbers_id'))
        batch_op.drop_index(batch_op.f('ix_phone_numbers_business_id'))

    op.drop_table('phone_numbers')
    with op.batch_alter_table('patient_intakes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_intakes_id'))

    op.drop_table('patient_intakes')
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_applications_id'))
        batch_op.drop_index(batch_op.f('ix_job_applications_business_id'))

    op.drop_table('job_applications')
    with op.batch_alter_table('insurance_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insurance_profiles_patient_id'))
        batch_op.drop_index(batch_op.f('ix_insurance_profiles_id'))

    op.drop_table('insurance_profiles')
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form_submissions_id'))
        batch_op.drop_index(batch_op.f('ix_form_submissions_business_id'))

    op.drop_table('form_submissions')
    with op.batch_alter_table('equipment_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_requests_id'))
        batch_op.drop_index(batch_op.f('ix_equipment_requests_business_id'))

    op.drop_table('equipment_requests')
    with op.batch_alter_table('ecom_suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ecom_suppliers_product_id'))
        batch_op.drop_index(batch_op.f('ix_ecom_suppliers_id'))

    op.drop_table('ecom_suppliers')
    with op.batch_alter_table('ecom_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ecom_listings_id'))
        batch_op.drop_index(batch_op.f('ix_ecom_listings_business_id'))

    op.drop_table('ecom_listings')
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deals_id'))
        batch_op.drop_index(batch_op.f('ix_deals_business_id'))

    op.drop_table('deals')
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_logs_id'))
        batch_op.drop_index(batch_op.f('ix_call_logs_call_sid'))

    op.drop_table('call_logs')
    with op.batch_alter_table('approval_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_approval_tokens_id'))

    op.drop_table('approval_tokens')
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflows_name'))
        batch_op.drop_index(batch_op.f('ix_workflows_id'))
        batch_op.drop_index(batch_op.f('ix_workflows_business_id'))

    op.drop_table('workflows')
    with op.batch_alter_table('webhook_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_configs_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_configs_business_id'))

    op.drop_table('webhook_configs')
    with op.batch_alter_table('smartboss_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smartboss_insights_id'))
        batch_op.drop_index(batch_op.f('ix_smartboss_insights_business_id'))

    op.drop_table('smartboss_insights')
    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipelines_id'))
        batch_op.drop_index(batch_op.f('ix_pipelines_business_id'))

    op.drop_table('pipelines')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_id'))
        batch_op.drop_index(batch_op.f('ix_patients_business_id'))

    op.drop_table('patients')
    with op.batch_alter_table('master_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_recommendations_id'))

    op.drop_table('master_recommendations')
    with op.batch_alter_table('marketing_forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketing_forms_id'))
        batch_op.drop_index(batch_op.f('ix_marketing_forms_business_id'))

    op.drop_table('marketing_forms')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_id'))
        batch_op.drop_index(batch_op.f('ix_leads_email'))
        batch_op.drop_index(batch_op.f('ix_leads_business_id'))

    op.drop_table('leads')
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_postings_title'))
        batch_op.drop_index(batch_op.f('ix_job_postings_id'))
        batch_op.drop_index(batch_op.f('ix_job_postings_business_id'))

    op.drop_table('job_postings')
    with op.batch_alter_table('ivr_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ivr_configs_id'))
        batch_op.drop_index(batch_op.f('ix_ivr_configs_business_id'))

    op.drop_table('ivr_configs')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoices_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_business_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('ecom_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ecom_products_id'))
        batch_op.drop_index(batch_op.f('ix_ecom_products_business_id'))

    op.drop_table('ecom_products')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_email'))
        batch_op.drop_index(batch_op.f('ix_contacts_business_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_id'))
        batch_op.drop_index(batch_op.f('ix_candidates_email'))
        batch_op.drop_index(batch_op.f('ix_candidates_business_id'))

    op.drop_table('candidates')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_name'))
        batch_op.drop_index(batch_op.f('ix_campaigns_id'))
        batch_op.drop_index(batch_op.f('ix_campaigns_business_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_business_id'))

    op.drop_table('appointments')
    with op.batch_alter_table('agent_queues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_queues_id'))
        batch_op.drop_index(batch_op.f('ix_agent_queues_business_id'))

    op.drop_table('agent_queues')
    with op.batch_alter_table('agent_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_definitions_id'))

    op.drop_table('agent_definitions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('supplier_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_products_name'))
        batch_op.drop_index(batch_op.f('ix_supplier_products_id'))

    op.drop_table('supplier_products')
    with op.batch_alter_table('dropship_directory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dropship_directory_name'))
        batch_op.drop_index(batch_op.f('ix_dropship_directory_id'))

    op.drop_table('dropship_directory')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_name'))
        batch_op.drop_index(batch_op.f('ix_businesses_id'))
        batch_op.drop_index(batch_op.f('ix_businesses_email'))

    op.drop_table('businesses')
    with op.batch_alter_table('agent_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_agent_tasks_agent_name'))

    op.drop_table('agent_tasks')
    with op.batch_alter_table('admin_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_alerts_id'))

    op.drop_table('admin_alerts')
    # ### end Alembic commands ###
