"""mo foundation and builder runtime

Revision ID: 0002_mo_builder
Revises: 0001_baseline
Create Date: 2026-08-26 09:15:39.154993
"""
from alembic import op
import sqlalchemy as sa


revision = '0002_mo_builder'
down_revision = '0001_baseline'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('builder_components',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('stack', sa.String(length=80), nullable=True),
    sa.Column('provenance', sa.String(length=200), nullable=True),
    sa.Column('license', sa.String(length=80), nullable=True),
    sa.Column('security_status', sa.String(length=32), nullable=False),
    sa.Column('dependencies_json', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builder_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builder_components_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('builder_projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('build_mode', sa.String(length=16), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_platform', sa.String(length=40), nullable=False),
    sa.Column('preferred_stack', sa.String(length=80), nullable=False),
    sa.Column('source_channel', sa.String(length=32), nullable=False),
    sa.Column('security_level', sa.String(length=24), nullable=False),
    sa.Column('data_classification', sa.String(length=24), nullable=False),
    sa.Column('deployment_target', sa.String(length=40), nullable=False),
    sa.Column('budget_usd', sa.Float(), nullable=True),
    sa.Column('constraints_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('workspace_path', sa.String(length=500), nullable=True),
    sa.Column('cost_model_usd', sa.Float(), nullable=False),
    sa.Column('cost_tokens', sa.Integer(), nullable=False),
    sa.Column('sandbox_seconds', sa.Float(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_builder_project_slug')
    )
    with op.batch_alter_table('builder_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builder_projects_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mo_agent_manifests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('model_policy_json', sa.Text(), nullable=False),
    sa.Column('tools_json', sa.Text(), nullable=False),
    sa.Column('permissions_json', sa.Text(), nullable=False),
    sa.Column('memory_policy_json', sa.Text(), nullable=False),
    sa.Column('knowledge_json', sa.Text(), nullable=False),
    sa.Column('autonomy_level', sa.String(length=24), nullable=False),
    sa.Column('budget_usd', sa.Float(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('approval_gates_json', sa.Text(), nullable=False),
    sa.Column('evaluation_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('kill_switch', sa.Boolean(), nullable=False),
    sa.Column('test_report_json', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', 'version', name='uq_mo_agent_ident')
    )
    with op.batch_alter_table('mo_agent_manifests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_agent_manifests_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mo_agent_manifests_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mo_approvals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=160), nullable=False),
    sa.Column('risk_tier', sa.String(length=16), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=True),
    sa.Column('resource_id', sa.String(length=120), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('required_approvals', sa.Integer(), nullable=False),
    sa.Column('approvals_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mo_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_approvals_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mo_audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_label', sa.String(length=160), nullable=True),
    sa.Column('source_channel', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=160), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=True),
    sa.Column('resource_id', sa.String(length=120), nullable=True),
    sa.Column('result_state', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_hash'),
    sa.UniqueConstraint('tenant_id', 'seq', name='uq_mo_audit_tenant_seq')
    )
    with op.batch_alter_table('mo_audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_mo_audit_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mo_audit_events_trace_id'), ['trace_id'], unique=False)
        batch_op.create_index('ix_mo_audit_tenant_occurred', ['tenant_id', 'occurred_at'], unique=False)

    op.create_table('mo_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('delivery_attempts', sa.Integer(), nullable=False),
    sa.Column('dead_lettered', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mo_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mo_events_topic'), ['topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_mo_events_trace_id'), ['trace_id'], unique=False)

    op.create_table('mo_tenants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('plan', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('safe_mode', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mo_tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_tenants_slug'), ['slug'], unique=True)

    op.create_table('mo_tools',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('required_scopes', sa.Text(), nullable=False),
    sa.Column('input_schema', sa.Text(), nullable=False),
    sa.Column('output_schema', sa.Text(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('credential_env_var', sa.String(length=120), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', 'version', name='uq_mo_tool_ident')
    )
    with op.batch_alter_table('mo_tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_tools_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_mo_tools_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('builder_agents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('manifest_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('canvas_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['builder_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builder_agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builder_agents_manifest_id'), ['manifest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_builder_agents_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_builder_agents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('builder_apis',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('protocol', sa.String(length=24), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_model', sa.String(length=120), nullable=True),
    sa.Column('operation', sa.String(length=40), nullable=True),
    sa.Column('input_schema_json', sa.Text(), nullable=False),
    sa.Column('output_schema_json', sa.Text(), nullable=False),
    sa.Column('requires_auth', sa.Boolean(), nullable=False),
    sa.Column('required_scopes_json', sa.Text(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('idempotent', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['builder_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builder_apis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builder_apis_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_builder_apis_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('builder_architectures',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('recommended', sa.String(length=40), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('alternatives_json', sa.Text(), nullable=False),
    sa.Column('tradeoffs_json', sa.Text(), nullable=False),
    sa.Column('scores_json', sa.Text(), nullable=False),
    sa.Column('infrastructure_json', sa.Text(), nullable=False),
    sa.Column('complexity', sa.String(length=16), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['builder_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builder_architectures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builder_architectures_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_builder_architectures_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('builder_assumptions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('impact', sa.String(length=16), nullable=False),
    sa.Column('confirmed_by', sa.String(length=64), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['builder_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builder_assumptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builder_assumptions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_builder_assumptions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('builder_builds',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('stages_json', sa.Text(), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('peak_rss_kb', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['builder_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builder_builds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builder_builds_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_builder_builds_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('builder_data_models',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('table_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fields_json', sa.Text(), nullable=False),
    sa.Column('relations_json', sa.Text(), nullable=False),
    sa.Column('indexes_json', sa.Text(), nullable=False),
    sa.Column('tenant_scoped', sa.Boolean(), nullable=False),
    sa.Column('soft_delete', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['builder_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builder_data_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builder_data_models_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_builder_data_models_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('builder_deployments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('approval_id', sa.String(length=64), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['builder_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builder_deployments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builder_deployments_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_builder_deployments_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('builder_files',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=40), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('generator', sa.String(length=120), nullable=True),
    sa.Column('is_custom_code', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['builder_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builder_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builder_files_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_builder_files_project_version', ['project_id', 'version'], unique=False)
        batch_op.create_index(batch_op.f('ix_builder_files_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('builder_integrations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('capability', sa.String(length=120), nullable=False),
    sa.Column('auth_kind', sa.String(length=40), nullable=False),
    sa.Column('credential_env_var', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['builder_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builder_integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builder_integrations_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_builder_integrations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('builder_pages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('route', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('requires_auth', sa.Boolean(), nullable=False),
    sa.Column('sections_json', sa.Text(), nullable=False),
    sa.Column('seo_json', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['builder_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builder_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builder_pages_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_builder_pages_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('builder_previews',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('entry_path', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['builder_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builder_previews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builder_previews_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_builder_previews_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('builder_project_graph',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('node_key', sa.String(length=160), nullable=False),
    sa.Column('node_type', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('attributes_json', sa.Text(), nullable=False),
    sa.Column('depends_on_json', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['builder_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builder_project_graph', schema=None) as batch_op:
        batch_op.create_index('ix_builder_graph_project_version', ['project_id', 'version'], unique=False)
        batch_op.create_index(batch_op.f('ix_builder_project_graph_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_builder_project_graph_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('builder_requirements',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('module', sa.String(length=80), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['builder_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builder_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builder_requirements_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_builder_requirements_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('builder_tests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('build_id', sa.String(length=64), nullable=True),
    sa.Column('suite', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['builder_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builder_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builder_tests_build_id'), ['build_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_builder_tests_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_builder_tests_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('builder_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('tree_sha256', sa.String(length=64), nullable=True),
    sa.Column('graph_snapshot', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['builder_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version', name='uq_builder_version')
    )
    with op.batch_alter_table('builder_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builder_versions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_builder_versions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('builder_workflows',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('trigger_type', sa.String(length=40), nullable=False),
    sa.Column('nodes_json', sa.Text(), nullable=False),
    sa.Column('edges_json', sa.Text(), nullable=False),
    sa.Column('compiled_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['builder_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builder_workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builder_workflows_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_builder_workflows_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('builder_workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builder_workflows_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_builder_workflows_project_id'))

    op.drop_table('builder_workflows')
    with op.batch_alter_table('builder_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builder_versions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_builder_versions_project_id'))

    op.drop_table('builder_versions')
    with op.batch_alter_table('builder_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builder_tests_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_builder_tests_project_id'))
        batch_op.drop_index(batch_op.f('ix_builder_tests_build_id'))

    op.drop_table('builder_tests')
    with op.batch_alter_table('builder_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builder_requirements_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_builder_requirements_project_id'))

    op.drop_table('builder_requirements')
    with op.batch_alter_table('builder_project_graph', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builder_project_graph_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_builder_project_graph_project_id'))
        batch_op.drop_index('ix_builder_graph_project_version')

    op.drop_table('builder_project_graph')
    with op.batch_alter_table('builder_previews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builder_previews_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_builder_previews_project_id'))

    op.drop_table('builder_previews')
    with op.batch_alter_table('builder_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builder_pages_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_builder_pages_project_id'))

    op.drop_table('builder_pages')
    with op.batch_alter_table('builder_integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builder_integrations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_builder_integrations_project_id'))

    op.drop_table('builder_integrations')
    with op.batch_alter_table('builder_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builder_files_tenant_id'))
        batch_op.drop_index('ix_builder_files_project_version')
        batch_op.drop_index(batch_op.f('ix_builder_files_project_id'))

    op.drop_table('builder_files')
    with op.batch_alter_table('builder_deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builder_deployments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_builder_deployments_project_id'))

    op.drop_table('builder_deployments')
    with op.batch_alter_table('builder_data_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builder_data_models_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_builder_data_models_project_id'))

    op.drop_table('builder_data_models')
    with op.batch_alter_table('builder_builds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builder_builds_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_builder_builds_project_id'))

    op.drop_table('builder_builds')
    with op.batch_alter_table('builder_assumptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builder_assumptions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_builder_assumptions_project_id'))

    op.drop_table('builder_assumptions')
    with op.batch_alter_table('builder_architectures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builder_architectures_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_builder_architectures_project_id'))

    op.drop_table('builder_architectures')
    with op.batch_alter_table('builder_apis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builder_apis_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_builder_apis_project_id'))

    op.drop_table('builder_apis')
    with op.batch_alter_table('builder_agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builder_agents_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_builder_agents_project_id'))
        batch_op.drop_index(batch_op.f('ix_builder_agents_manifest_id'))

    op.drop_table('builder_agents')
    with op.batch_alter_table('mo_tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_tools_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mo_tools_name'))

    op.drop_table('mo_tools')
    with op.batch_alter_table('mo_tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_tenants_slug'))

    op.drop_table('mo_tenants')
    with op.batch_alter_table('mo_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_events_trace_id'))
        batch_op.drop_index(batch_op.f('ix_mo_events_topic'))
        batch_op.drop_index(batch_op.f('ix_mo_events_tenant_id'))

    op.drop_table('mo_events')
    with op.batch_alter_table('mo_audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_mo_audit_tenant_occurred')
        batch_op.drop_index(batch_op.f('ix_mo_audit_events_trace_id'))
        batch_op.drop_index(batch_op.f('ix_mo_audit_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mo_audit_events_action'))

    op.drop_table('mo_audit_events')
    with op.batch_alter_table('mo_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_approvals_tenant_id'))

    op.drop_table('mo_approvals')
    with op.batch_alter_table('mo_agent_manifests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_agent_manifests_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mo_agent_manifests_project_id'))

    op.drop_table('mo_agent_manifests')
    with op.batch_alter_table('builder_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builder_projects_tenant_id'))

    op.drop_table('builder_projects')
    with op.batch_alter_table('builder_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builder_components_tenant_id'))

    op.drop_table('builder_components')
    # ### end Alembic commands ###
