"""voice sessions and turns

Revision ID: 0004_voice
Revises: 0003_user_tenancy
Create Date: 2026-09-28 18:14:46.324680
"""
from alembic import op
import sqlalchemy as sa


revision = '0004_voice'
down_revision = '0003_user_tenancy'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mo_voice_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('awake_until', sa.DateTime(), nullable=True),
    sa.Column('focus_project_id', sa.String(length=64), nullable=True),
    sa.Column('pending_intent', sa.String(length=80), nullable=True),
    sa.Column('pending_slots_json', sa.Text(), nullable=False),
    sa.Column('last_response', sa.Text(), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mo_voice_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_voice_sessions_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mo_voice_sessions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mo_voice_turns',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('wake_detected', sa.Boolean(), nullable=False),
    sa.Column('intent', sa.String(length=80), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('slots_json', sa.Text(), nullable=False),
    sa.Column('result_state', sa.String(length=40), nullable=False),
    sa.Column('reply', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['mo_voice_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'seq', name='uq_voice_turn_seq')
    )
    with op.batch_alter_table('mo_voice_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_voice_turns_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mo_voice_turns_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mo_voice_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_voice_turns_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mo_voice_turns_session_id'))

    op.drop_table('mo_voice_turns')
    with op.batch_alter_table('mo_voice_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_voice_sessions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mo_voice_sessions_actor_id'))

    op.drop_table('mo_voice_sessions')
    # ### end Alembic commands ###
