"""platform knowledge memory orchestration control protocols evaluation

Revision ID: 0005_platform
Revises: 0004_voice
Create Date: 2026-09-28 18:36:01.691559
"""
from alembic import op
import sqlalchemy as sa


revision = '0005_platform'
down_revision = '0004_voice'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mo_autonomy_policies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('max_level', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'subject', name='uq_mo_autonomy_subject')
    )
    with op.batch_alter_table('mo_autonomy_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_autonomy_policies_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mo_eval_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('suite', sa.String(length=160), nullable=False),
    sa.Column('target', sa.String(length=160), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('passed_count', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('results_json', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mo_eval_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_eval_runs_suite'), ['suite'], unique=False)
        batch_op.create_index(batch_op.f('ix_mo_eval_runs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mo_knowledge_docs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('classification', sa.String(length=16), nullable=False),
    sa.Column('allowed_scopes_json', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('embedder', sa.String(length=60), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'content_hash', name='uq_mo_knowledge_doc_hash')
    )
    with op.batch_alter_table('mo_knowledge_docs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_knowledge_docs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mo_memories',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('shared', sa.Boolean(), nullable=False),
    sa.Column('classification', sa.String(length=16), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('terms_json', sa.Text(), nullable=False),
    sa.Column('vector_json', sa.Text(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('redactions_json', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mo_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_memories_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mo_memories_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_mo_memories_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mo_protocol_peers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('credential_env_var', sa.String(length=120), nullable=True),
    sa.Column('allowed_tools_json', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_mo_peer_name')
    )
    with op.batch_alter_table('mo_protocol_peers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_protocol_peers_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mo_reversible_actions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=160), nullable=False),
    sa.Column('resource', sa.String(length=200), nullable=True),
    sa.Column('undo_tool', sa.String(length=120), nullable=True),
    sa.Column('undo_payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mo_reversible_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_reversible_actions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mo_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('spec_json', sa.Text(), nullable=False),
    sa.Column('budget_usd', sa.Float(), nullable=False),
    sa.Column('spent_usd', sa.Float(), nullable=False),
    sa.Column('autonomy_level', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mo_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_runs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mo_shadow_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('action', sa.String(length=160), nullable=False),
    sa.Column('proposal_json', sa.Text(), nullable=False),
    sa.Column('human_json', sa.Text(), nullable=True),
    sa.Column('agreed', sa.Boolean(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mo_shadow_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_shadow_records_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_mo_shadow_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mo_knowledge_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('doc_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('terms_json', sa.Text(), nullable=False),
    sa.Column('vector_json', sa.Text(), nullable=False),
    sa.Column('entities_json', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['mo_knowledge_docs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mo_knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_knowledge_chunks_doc_id'), ['doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mo_knowledge_chunks_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mo_run_steps',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('step_key', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('target', sa.String(length=160), nullable=False),
    sa.Column('depends_on_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('result_state', sa.String(length=40), nullable=True),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('approval_id', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['mo_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'step_key', name='uq_mo_run_step_key')
    )
    with op.batch_alter_table('mo_run_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_run_steps_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mo_run_steps_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mo_run_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_run_steps_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mo_run_steps_run_id'))

    op.drop_table('mo_run_steps')
    with op.batch_alter_table('mo_knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_knowledge_chunks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mo_knowledge_chunks_doc_id'))

    op.drop_table('mo_knowledge_chunks')
    with op.batch_alter_table('mo_shadow_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_shadow_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mo_shadow_records_subject'))

    op.drop_table('mo_shadow_records')
    with op.batch_alter_table('mo_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_runs_tenant_id'))

    op.drop_table('mo_runs')
    with op.batch_alter_table('mo_reversible_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_reversible_actions_tenant_id'))

    op.drop_table('mo_reversible_actions')
    with op.batch_alter_table('mo_protocol_peers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_protocol_peers_tenant_id'))

    op.drop_table('mo_protocol_peers')
    with op.batch_alter_table('mo_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_memories_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mo_memories_kind'))
        batch_op.drop_index(batch_op.f('ix_mo_memories_actor_id'))

    op.drop_table('mo_memories')
    with op.batch_alter_table('mo_knowledge_docs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_knowledge_docs_tenant_id'))

    op.drop_table('mo_knowledge_docs')
    with op.batch_alter_table('mo_eval_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_eval_runs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mo_eval_runs_suite'))

    op.drop_table('mo_eval_runs')
    with op.batch_alter_table('mo_autonomy_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_autonomy_policies_tenant_id'))

    op.drop_table('mo_autonomy_policies')
    # ### end Alembic commands ###
