"""authority grants receipts agents releases dependencies

Revision ID: 0006_authority
Revises: 0005_platform
Create Date: 2026-09-28 20:39:45.771708
"""
from alembic import op
import sqlalchemy as sa


revision = '0006_authority'
down_revision = '0005_platform'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mo_agent_releases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('agent_name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('manifest_json', sa.Text(), nullable=False),
    sa.Column('manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scan_json', sa.Text(), nullable=True),
    sa.Column('eval_run_id', sa.String(length=64), nullable=True),
    sa.Column('eval_report_hash', sa.String(length=64), nullable=True),
    sa.Column('approval_id', sa.String(length=64), nullable=True),
    sa.Column('canary_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('previous_release_id', sa.String(length=64), nullable=True),
    sa.Column('stop_reason', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'agent_name', 'version', name='uq_mo_release_version')
    )
    with op.batch_alter_table('mo_agent_releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_agent_releases_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_mo_agent_releases_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mo_agents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allowed_tools_json', sa.Text(), nullable=False),
    sa.Column('risk_ceiling', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_mo_agent_name')
    )
    with op.batch_alter_table('mo_agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_agents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mo_capability_grants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('approval_id', sa.String(length=64), nullable=False),
    sa.Column('tool', sa.String(length=160), nullable=False),
    sa.Column('action', sa.String(length=160), nullable=False),
    sa.Column('resource', sa.String(length=500), nullable=False),
    sa.Column('args_hash', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('mo_capability_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_capability_grants_approval_id'), ['approval_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mo_capability_grants_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mo_dependencies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('license', sa.String(length=200), nullable=True),
    sa.Column('license_class', sa.String(length=24), nullable=False),
    sa.Column('license_text_hash', sa.String(length=64), nullable=True),
    sa.Column('usage', sa.String(length=300), nullable=True),
    sa.Column('attribution_required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', 'version', name='uq_mo_dependency')
    )
    with op.batch_alter_table('mo_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_dependencies_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mo_receipts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('mission_id', sa.String(length=64), nullable=True),
    sa.Column('tool', sa.String(length=160), nullable=False),
    sa.Column('action', sa.String(length=160), nullable=False),
    sa.Column('resource', sa.String(length=500), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('grant_id', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('output_hash', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_mo_receipt_idem')
    )
    with op.batch_alter_table('mo_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_receipts_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mo_receipts_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mo_receipts_trace_id'), ['trace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mo_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_receipts_trace_id'))
        batch_op.drop_index(batch_op.f('ix_mo_receipts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mo_receipts_mission_id'))

    op.drop_table('mo_receipts')
    with op.batch_alter_table('mo_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_dependencies_tenant_id'))

    op.drop_table('mo_dependencies')
    with op.batch_alter_table('mo_capability_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_capability_grants_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mo_capability_grants_approval_id'))

    op.drop_table('mo_capability_grants')
    with op.batch_alter_table('mo_agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_agents_tenant_id'))

    op.drop_table('mo_agents')
    with op.batch_alter_table('mo_agent_releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_agent_releases_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mo_agent_releases_agent_name'))

    op.drop_table('mo_agent_releases')
    # ### end Alembic commands ###
