"""shared state kv and a2a nonces

Revision ID: 0007_shared_state
Revises: 0006_authority
Create Date: 2026-09-28 20:56:00.702807
"""
from alembic import op
import sqlalchemy as sa


revision = '0007_shared_state'
down_revision = '0006_authority'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mo_a2a_nonces',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('peer', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.String(length=128), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'peer', 'nonce', name='uq_mo_a2a_nonce')
    )
    with op.batch_alter_table('mo_a2a_nonces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_a2a_nonces_seen_at'), ['seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mo_a2a_nonces_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mo_kv',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('namespace', sa.String(length=80), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'namespace', 'key', name='uq_mo_kv')
    )
    with op.batch_alter_table('mo_kv', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mo_kv_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mo_kv', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_kv_tenant_id'))

    op.drop_table('mo_kv')
    with op.batch_alter_table('mo_a2a_nonces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mo_a2a_nonces_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mo_a2a_nonces_seen_at'))

    op.drop_table('mo_a2a_nonces')
    # ### end Alembic commands ###
