"""voice persona

Revision ID: 0008_voice_persona
Revises: 0007_shared_state
Create Date: 2026-09-28 21:51:34.045336
"""
from alembic import op
import sqlalchemy as sa


revision = '0008_voice_persona'
down_revision = '0007_shared_state'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mo_voice_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('persona_json', sa.Text(), nullable=False, server_default='{}'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mo_voice_sessions', schema=None) as batch_op:
        batch_op.drop_column('persona_json')

    # ### end Alembic commands ###
