"""
Seed data for the Dropship Directory — vetted wholesalers, distributors,
and dropship platforms covering USA, EU, Asia, and global.
"""
import json
from .models import DropshipDirectory


SEED_DATA = [
    # ── USA Dropship Platforms ────────────────────────────────────────────────
    {
        "name": "Spocket",
        "country": "USA / EU",
        "region": "USA",
        "platform_type": "dropshipper",
        "categories": json.dumps(["Fashion", "Home", "Beauty", "Electronics", "Jewelry", "Pet"]),
        "website": "spocket.co",
        "min_order_usd": 0,
        "shipping_days_usa": 3,
        "shipping_days_intl": 10,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": True,
        "description": "Top dropshipping platform with US & EU suppliers. 2–5 day shipping. Integrates with Shopify, WooCommerce, BigCommerce, Wix.",
        "rating": 4.7,
    },
    {
        "name": "Modalyst",
        "country": "USA",
        "region": "USA",
        "platform_type": "dropshipper",
        "categories": json.dumps(["Fashion", "Accessories", "Beauty", "Home", "Kids"]),
        "website": "modalyst.co",
        "min_order_usd": 0,
        "shipping_days_usa": 4,
        "shipping_days_intl": 14,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": True,
        "description": "Curated US dropshipping marketplace. Fashion-forward inventory with independent brands. No minimum order.",
        "rating": 4.5,
    },
    {
        "name": "Wholesale2B",
        "country": "USA",
        "region": "USA",
        "platform_type": "aggregator",
        "categories": json.dumps(["General", "Electronics", "Toys", "Sports", "Home", "Clothing"]),
        "website": "wholesale2b.com",
        "min_order_usd": 0,
        "shipping_days_usa": 5,
        "shipping_days_intl": 18,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": True,
        "description": "1M+ products from US suppliers. Automates order fulfillment to Amazon, eBay, Shopify, WooCommerce.",
        "rating": 4.3,
    },
    {
        "name": "Zendrop",
        "country": "USA",
        "region": "USA",
        "platform_type": "dropshipper",
        "categories": json.dumps(["General", "Health", "Beauty", "Home", "Electronics", "Fitness"]),
        "website": "zendrop.com",
        "min_order_usd": 0,
        "shipping_days_usa": 5,
        "shipping_days_intl": 15,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": True,
        "description": "Built for Shopify. 1M+ products, US warehouse options, automated fulfillment, custom branding & packaging.",
        "rating": 4.6,
    },
    {
        "name": "Printful",
        "country": "USA",
        "region": "USA",
        "platform_type": "POD",
        "categories": json.dumps(["Apparel", "Accessories", "Home Decor", "Print-on-Demand"]),
        "website": "printful.com",
        "min_order_usd": 0,
        "shipping_days_usa": 4,
        "shipping_days_intl": 12,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": True,
        "description": "Leading print-on-demand + dropshipping. USA fulfillment centers. Integrates with Shopify, Etsy, Amazon, eBay, WooCommerce.",
        "rating": 4.8,
    },
    {
        "name": "Printify",
        "country": "USA",
        "region": "USA",
        "platform_type": "POD",
        "categories": json.dumps(["Apparel", "Mugs", "Phone Cases", "Home", "Print-on-Demand"]),
        "website": "printify.com",
        "min_order_usd": 0,
        "shipping_days_usa": 5,
        "shipping_days_intl": 14,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": True,
        "description": "Print-on-demand network with 80+ print providers worldwide. Competitive pricing, USA print facilities.",
        "rating": 4.6,
    },
    {
        "name": "Inventory Source",
        "country": "USA",
        "region": "USA",
        "platform_type": "aggregator",
        "categories": json.dumps(["General", "Electronics", "Sporting Goods", "Toys", "Automotive"]),
        "website": "inventorysource.com",
        "min_order_usd": 0,
        "shipping_days_usa": 4,
        "shipping_days_intl": 14,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": True,
        "description": "250+ US suppliers, automated product uploads to Amazon, eBay, Shopify. Real-time inventory sync.",
        "rating": 4.4,
    },
    {
        "name": "Sunrise Wholesale",
        "country": "USA",
        "region": "USA",
        "platform_type": "wholesaler",
        "categories": json.dumps(["Electronics", "Home & Garden", "Sports", "Gifts", "Jewelry"]),
        "website": "sunrisewholesalemerchandise.com",
        "min_order_usd": 0,
        "shipping_days_usa": 2,
        "shipping_days_intl": 12,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": False,
        "description": "USA-based dropship wholesaler, 30,000+ products. Ships in 1–2 business days from CA warehouse.",
        "rating": 4.3,
    },
    {
        "name": "Kole Imports",
        "country": "USA",
        "region": "USA",
        "platform_type": "wholesaler",
        "categories": json.dumps(["General Merchandise", "Seasonal", "Home", "Toys", "Beauty"]),
        "website": "koleimports.com",
        "min_order_usd": 50,
        "shipping_days_usa": 3,
        "shipping_days_intl": 15,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": False,
        "description": "Carson, CA wholesaler. Deep-discount general merchandise. Low MOQ, ships nationwide.",
        "rating": 4.2,
    },
    {
        "name": "SaleHoo",
        "country": "USA / Global",
        "region": "Global",
        "platform_type": "aggregator",
        "categories": json.dumps(["General", "Electronics", "Clothing", "Home", "Sports"]),
        "website": "salehoo.com",
        "min_order_usd": 0,
        "shipping_days_usa": 5,
        "shipping_days_intl": 20,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": True,
        "description": "8,000+ vetted wholesale/dropship suppliers. Directory + market research tools for Amazon & eBay sellers.",
        "rating": 4.4,
    },
    {
        "name": "Worldwide Brands",
        "country": "USA",
        "region": "USA",
        "platform_type": "aggregator",
        "categories": json.dumps(["General", "Electronics", "Fashion", "Home", "Sports", "Automotive"]),
        "website": "worldwidebrands.com",
        "min_order_usd": 0,
        "shipping_days_usa": 4,
        "shipping_days_intl": 16,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": False,
        "description": "16M+ certified wholesale products. Only certified factory-authorized suppliers. Lifetime membership directory.",
        "rating": 4.3,
    },
    # ── USA Major Distributors ───────────────────────────────────────────────
    {
        "name": "Ingram Micro",
        "country": "USA",
        "region": "USA",
        "platform_type": "distributor",
        "categories": json.dumps(["Electronics", "IT Products", "Networking", "Software", "Cloud"]),
        "website": "ingrammicro.com",
        "min_order_usd": 500,
        "shipping_days_usa": 2,
        "shipping_days_intl": 10,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": True,
        "description": "World's largest technology distributor. Billions in revenue. 200,000+ products across IT, cloud, and mobility.",
        "rating": 4.5,
    },
    {
        "name": "TD Synnex",
        "country": "USA",
        "region": "USA",
        "platform_type": "distributor",
        "categories": json.dumps(["Electronics", "IT", "Peripherals", "Software", "Security"]),
        "website": "tdsynnex.com",
        "min_order_usd": 500,
        "shipping_days_usa": 2,
        "shipping_days_intl": 10,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": True,
        "description": "Top global IT distributor. 150,000+ products. APIs available for resellers and ecommerce.",
        "rating": 4.5,
    },
    {
        "name": "SanMar Corporation",
        "country": "USA",
        "region": "USA",
        "platform_type": "distributor",
        "categories": json.dumps(["Apparel", "T-Shirts", "Outerwear", "Bags", "Promotional"]),
        "website": "sanmar.com",
        "min_order_usd": 50,
        "shipping_days_usa": 3,
        "shipping_days_intl": 14,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": True,
        "description": "Largest US wholesale apparel distributor. Brands: Port & Company, Nike, Carhartt, New Era. 100+ US locations.",
        "rating": 4.7,
    },
    {
        "name": "S&S Activewear",
        "country": "USA",
        "region": "USA",
        "platform_type": "distributor",
        "categories": json.dumps(["Activewear", "T-Shirts", "Hoodies", "Hats", "Bags"]),
        "website": "ssactivewear.com",
        "min_order_usd": 0,
        "shipping_days_usa": 2,
        "shipping_days_intl": 12,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": True,
        "description": "No-minimum wholesale activewear. Brands include Nike, Under Armour, Adidas. Ships next day from US hubs.",
        "rating": 4.6,
    },
    {
        "name": "Faire",
        "country": "USA",
        "region": "USA",
        "platform_type": "wholesaler",
        "categories": json.dumps(["Home Decor", "Gifts", "Food & Beverage", "Beauty", "Kids", "Apparel"]),
        "website": "faire.com",
        "min_order_usd": 100,
        "shipping_days_usa": 5,
        "shipping_days_intl": 18,
        "has_usa_warehouse": True,
        "dropship_ready": False,
        "api_integration": True,
        "description": "Wholesale marketplace for independent brands. 100,000+ brands, net-60 payment terms, free returns on first order.",
        "rating": 4.6,
    },
    {
        "name": "Tundra Wholesale",
        "country": "USA",
        "region": "USA",
        "platform_type": "wholesaler",
        "categories": json.dumps(["Home", "Food", "Beauty", "Apparel", "Toys", "Office"]),
        "website": "tundra.com",
        "min_order_usd": 0,
        "shipping_days_usa": 4,
        "shipping_days_intl": 16,
        "has_usa_warehouse": True,
        "dropship_ready": False,
        "api_integration": False,
        "description": "Zero-fee wholesale marketplace. Brands ship direct to buyer. Free to list and buy. Alternative to Faire.",
        "rating": 4.3,
    },
    # ── International with USA Warehouses ────────────────────────────────────
    {
        "name": "CJdropshipping",
        "country": "China",
        "region": "Asia",
        "platform_type": "dropshipper",
        "categories": json.dumps(["General", "Electronics", "Fashion", "Home", "Sports", "Jewelry"]),
        "website": "cjdropshipping.com",
        "min_order_usd": 0,
        "shipping_days_usa": 5,
        "shipping_days_intl": 12,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": True,
        "description": "China-based with USA/EU warehouses. 400,000+ products, free product sourcing, custom packaging. Ships in 3–7 days from USA warehouse.",
        "rating": 4.5,
    },
    {
        "name": "Alibaba.com",
        "country": "China",
        "region": "Asia",
        "platform_type": "wholesaler",
        "categories": json.dumps(["General", "Electronics", "Machinery", "Apparel", "Home", "Industrial"]),
        "website": "alibaba.com",
        "min_order_usd": 100,
        "shipping_days_usa": 14,
        "shipping_days_intl": 21,
        "has_usa_warehouse": False,
        "dropship_ready": False,
        "api_integration": True,
        "description": "World's largest B2B wholesale marketplace. 10M+ suppliers, factory-direct pricing, Trade Assurance program.",
        "rating": 4.4,
    },
    {
        "name": "AliExpress (Dropshipping)",
        "country": "China",
        "region": "Asia",
        "platform_type": "dropshipper",
        "categories": json.dumps(["General", "Electronics", "Fashion", "Home", "Beauty", "Toys"]),
        "website": "aliexpress.com",
        "min_order_usd": 0,
        "shipping_days_usa": 10,
        "shipping_days_intl": 20,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": True,
        "description": "Retail/dropship arm of Alibaba. 100M+ products, AliExpress Direct for fast US shipping, AliDropship plugin integration.",
        "rating": 4.2,
    },
    {
        "name": "DHgate",
        "country": "China",
        "region": "Asia",
        "platform_type": "wholesaler",
        "categories": json.dumps(["Electronics", "Fashion", "Jewelry", "Sports", "Wedding", "Health"]),
        "website": "dhgate.com",
        "min_order_usd": 10,
        "shipping_days_usa": 10,
        "shipping_days_intl": 20,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": False,
        "description": "China wholesale B2B/B2C. Low MOQ, buyer protection, US/EU warehouses available on many items. Popular for fashion & electronics.",
        "rating": 4.1,
    },
    {
        "name": "Banggood",
        "country": "China",
        "region": "Asia",
        "platform_type": "dropshipper",
        "categories": json.dumps(["Electronics", "RC Toys", "Tools", "Home", "Sports", "Garden"]),
        "website": "banggood.com",
        "min_order_usd": 0,
        "shipping_days_usa": 7,
        "shipping_days_intl": 15,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": True,
        "description": "Chinese retailer with dropship program. USA/EU/AU warehouses. Strong in electronics, RC hobbies, tools.",
        "rating": 4.1,
    },
    {
        "name": "Made-in-China.com",
        "country": "China",
        "region": "Asia",
        "platform_type": "wholesaler",
        "categories": json.dumps(["Industrial", "Machinery", "Electronics", "Consumer Goods", "Auto Parts"]),
        "website": "made-in-china.com",
        "min_order_usd": 200,
        "shipping_days_usa": 14,
        "shipping_days_intl": 25,
        "has_usa_warehouse": False,
        "dropship_ready": False,
        "api_integration": False,
        "description": "Verified Chinese manufacturers. Strong in industrial, OEM, and custom manufacturing. Good for private label.",
        "rating": 4.0,
    },
    # ── European Suppliers ────────────────────────────────────────────────────
    {
        "name": "BigBuy",
        "country": "Spain",
        "region": "EU",
        "platform_type": "dropshipper",
        "categories": json.dumps(["General", "Electronics", "Toys", "Sports", "Home", "Beauty"]),
        "website": "bigbuy.eu",
        "min_order_usd": 0,
        "shipping_days_usa": 20,
        "shipping_days_intl": 7,
        "has_usa_warehouse": False,
        "dropship_ready": True,
        "api_integration": True,
        "description": "Europe's leading dropshipping wholesaler. 200,000+ products, 24-language support, ships to 34 EU countries in 3–5 days.",
        "rating": 4.4,
    },
    {
        "name": "VidaXL",
        "country": "Netherlands",
        "region": "EU",
        "platform_type": "wholesaler",
        "categories": json.dumps(["Furniture", "Garden", "Sports", "Automotive", "Home"]),
        "website": "vidaxl.com",
        "min_order_usd": 0,
        "shipping_days_usa": 18,
        "shipping_days_intl": 5,
        "has_usa_warehouse": False,
        "dropship_ready": True,
        "api_integration": True,
        "description": "Dutch dropship wholesaler. 90,000+ home/garden/furniture products. Ships across EU in 3–5 days. API available.",
        "rating": 4.2,
    },
    {
        "name": "Printify (EU)",
        "country": "Latvia / EU",
        "region": "EU",
        "platform_type": "POD",
        "categories": json.dumps(["Apparel", "Print-on-Demand", "Mugs", "Accessories", "Home Decor"]),
        "website": "printify.com",
        "min_order_usd": 0,
        "shipping_days_usa": 14,
        "shipping_days_intl": 5,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": True,
        "description": "EU print-on-demand network with providers across Europe. Also has US fulfillment centers. Etsy top integration partner.",
        "rating": 4.5,
    },
    {
        "name": "Brandsdistribution",
        "country": "Italy",
        "region": "EU",
        "platform_type": "distributor",
        "categories": json.dumps(["Luxury Fashion", "Clothing", "Shoes", "Bags", "Accessories"]),
        "website": "brandsdistribution.com",
        "min_order_usd": 200,
        "shipping_days_usa": 12,
        "shipping_days_intl": 4,
        "has_usa_warehouse": False,
        "dropship_ready": True,
        "api_integration": True,
        "description": "Italian luxury & fashion B2B dropshipper. 80,000+ items from 200+ brands (Nike, Adidas, Guess). Ships EU in 24–48hrs.",
        "rating": 4.3,
    },
    # ── India ─────────────────────────────────────────────────────────────────
    {
        "name": "IndiaMART",
        "country": "India",
        "region": "India",
        "platform_type": "wholesaler",
        "categories": json.dumps(["General", "Industrial", "Apparel", "Food", "Electronics", "Handicrafts"]),
        "website": "indiamart.com",
        "min_order_usd": 100,
        "shipping_days_usa": 18,
        "shipping_days_intl": 12,
        "has_usa_warehouse": False,
        "dropship_ready": False,
        "api_integration": False,
        "description": "India's largest B2B marketplace. 7M+ suppliers, strong in textiles, handicrafts, pharma, industrial goods.",
        "rating": 4.1,
    },
    {
        "name": "TradeIndia",
        "country": "India",
        "region": "India",
        "platform_type": "wholesaler",
        "categories": json.dumps(["Textiles", "Engineering", "Chemicals", "Food", "Handicrafts", "Gems"]),
        "website": "tradeindia.com",
        "min_order_usd": 100,
        "shipping_days_usa": 20,
        "shipping_days_intl": 14,
        "has_usa_warehouse": False,
        "dropship_ready": False,
        "api_integration": False,
        "description": "Indian wholesale directory. Strong in textiles, engineering products, spices, gems & jewelry. Good for private label.",
        "rating": 3.9,
    },
    # ── Canada ───────────────────────────────────────────────────────────────
    {
        "name": "Canadadrugs / Wholesale Club",
        "country": "Canada",
        "region": "USA",
        "platform_type": "wholesaler",
        "categories": json.dumps(["Food", "Household", "Beverage", "Health", "Beauty"]),
        "website": "wholesaleclub.ca",
        "min_order_usd": 200,
        "shipping_days_usa": 5,
        "shipping_days_intl": 3,
        "has_usa_warehouse": False,
        "dropship_ready": False,
        "api_integration": False,
        "description": "Canada's wholesale club. Cross-border shipping available. Great for US sellers sourcing from Canada.",
        "rating": 4.0,
    },
    # ── Mexico / LatAm ────────────────────────────────────────────────────────
    {
        "name": "Mercado Libre B2B",
        "country": "Mexico / LatAm",
        "region": "LatAm",
        "platform_type": "wholesaler",
        "categories": json.dumps(["General", "Electronics", "Fashion", "Home", "Automotive"]),
        "website": "mercadolibre.com",
        "min_order_usd": 50,
        "shipping_days_usa": 10,
        "shipping_days_intl": 5,
        "has_usa_warehouse": False,
        "dropship_ready": False,
        "api_integration": True,
        "description": "LatAm's largest marketplace/B2B. 20+ countries, strong logistics network, good for cross-border LatAm selling.",
        "rating": 4.0,
    },
    # ── Global / Multi-Region ─────────────────────────────────────────────────
    {
        "name": "Doba",
        "country": "USA",
        "region": "Global",
        "platform_type": "aggregator",
        "categories": json.dumps(["General", "Electronics", "Sports", "Home", "Clothing", "Outdoor"]),
        "website": "doba.com",
        "min_order_usd": 0,
        "shipping_days_usa": 4,
        "shipping_days_intl": 16,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": True,
        "description": "2M+ dropship products aggregated from hundreds of US suppliers. One-click export to Amazon, eBay, Shopify.",
        "rating": 4.2,
    },
    {
        "name": "Global Sources",
        "country": "Hong Kong",
        "region": "Asia",
        "platform_type": "wholesaler",
        "categories": json.dumps(["Electronics", "Fashion", "Home", "Beauty", "Gifts", "Sporting Goods"]),
        "website": "globalsources.com",
        "min_order_usd": 200,
        "shipping_days_usa": 14,
        "shipping_days_intl": 10,
        "has_usa_warehouse": False,
        "dropship_ready": False,
        "api_integration": False,
        "description": "Asia's leading B2B sourcing platform. 10M+ products, factory audits, trade shows. Strong for Amazon FBA sourcing.",
        "rating": 4.2,
    },
    {
        "name": "Oberlo (via Shopify)",
        "country": "Global",
        "region": "Global",
        "platform_type": "dropshipper",
        "categories": json.dumps(["General", "Fashion", "Electronics", "Home", "Beauty"]),
        "website": "shopify.com/dropshipping",
        "min_order_usd": 0,
        "shipping_days_usa": 10,
        "shipping_days_intl": 20,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": True,
        "description": "Shopify's native dropshipping solution (integrated into Shopify). Access to US & global suppliers via Shopify Collective.",
        "rating": 4.3,
    },
    {
        "name": "Dropified",
        "country": "USA",
        "region": "USA",
        "platform_type": "dropshipper",
        "categories": json.dumps(["General", "Health", "Beauty", "Electronics", "Fitness"]),
        "website": "dropified.com",
        "min_order_usd": 0,
        "shipping_days_usa": 5,
        "shipping_days_intl": 18,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": True,
        "description": "Automation tool for dropshipping from AliExpress, eBay, and US suppliers to Shopify, WooCommerce. Chrome extension.",
        "rating": 4.2,
    },
    {
        "name": "Teespring / Spring",
        "country": "USA",
        "region": "USA",
        "platform_type": "POD",
        "categories": json.dumps(["Apparel", "Print-on-Demand", "Accessories", "Home Decor"]),
        "website": "spri.ng",
        "min_order_usd": 0,
        "shipping_days_usa": 7,
        "shipping_days_intl": 14,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": True,
        "description": "Creator-focused POD platform. Sell custom merch with no upfront costs. Integrates with YouTube, TikTok, Twitch.",
        "rating": 4.1,
    },
    # ── Pet Food & Pet Supplies ───────────────────────────────────────────────
    {
        "name": "PetEdge Wholesale",
        "country": "USA",
        "region": "USA",
        "platform_type": "wholesaler",
        "categories": json.dumps(["Pet Food", "Pet Supplies", "Dog", "Cat", "Bird", "Grooming"]),
        "website": "petedge.com",
        "min_order_usd": 100,
        "shipping_days_usa": 3,
        "shipping_days_intl": 14,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": False,
        "description": "USA pet industry wholesale supplier. 10,000+ pet supplies, food, grooming, cages, toys. Low MOQ, ships nationwide.",
        "rating": 4.4,
    },
    {
        "name": "Pet Food Suppliers USA",
        "country": "USA",
        "region": "USA",
        "platform_type": "dropshipper",
        "categories": json.dumps(["Pet Food", "Dog Food", "Cat Food", "Bird Food", "Fish Food", "Pet Treats"]),
        "website": "petfoodsuppliers.com",
        "min_order_usd": 0,
        "shipping_days_usa": 2,
        "shipping_days_intl": 10,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": True,
        "description": "USA-based dropship platform for pet food. Brands: Blue Buffalo, Purina, Royal Canin. 2-day USA shipping, blind dropship available.",
        "rating": 4.6,
    },
    {
        "name": "Chewy Business / B2B",
        "country": "USA",
        "region": "USA",
        "platform_type": "wholesaler",
        "categories": json.dumps(["Pet Food", "Pet Medications", "Pet Supplies", "Dog", "Cat", "Fish", "Bird"]),
        "website": "chewy.com/b2b",
        "min_order_usd": 200,
        "shipping_days_usa": 2,
        "shipping_days_intl": 0,
        "has_usa_warehouse": True,
        "dropship_ready": False,
        "api_integration": True,
        "description": "Chewy's B2B wholesale division. Bulk pet food & supplies at wholesale pricing. USA only. Fast 1-2 day shipping.",
        "rating": 4.7,
    },
    {
        "name": "NutriSource Pet Foods",
        "country": "USA",
        "region": "USA",
        "platform_type": "distributor",
        "categories": json.dumps(["Pet Food", "Premium Dog Food", "Premium Cat Food", "Grain-Free", "Natural Pet Food"]),
        "website": "nutrisourcepetfoods.com",
        "min_order_usd": 300,
        "shipping_days_usa": 4,
        "shipping_days_intl": 0,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": False,
        "description": "USA manufacturer & distributor of premium pet food. Natural, grain-free options. Wholesale to pet stores and online sellers.",
        "rating": 4.5,
    },
    {
        "name": "Global Pet Foods Wholesale",
        "country": "Canada",
        "region": "USA",
        "platform_type": "wholesaler",
        "categories": json.dumps(["Pet Food", "Organic Pet Food", "Pet Treats", "Holistic Pet Food", "Dog", "Cat"]),
        "website": "globalpetfoods.com",
        "min_order_usd": 150,
        "shipping_days_usa": 5,
        "shipping_days_intl": 3,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": False,
        "description": "North American wholesale pet food distributor. Specialises in organic, holistic and natural pet foods. Ships USA & Canada.",
        "rating": 4.3,
    },
    {
        "name": "Pet Supplies Dropship Hub",
        "country": "USA",
        "region": "USA",
        "platform_type": "dropshipper",
        "categories": json.dumps(["Pet Food", "Pet Accessories", "Dog Collars", "Cat Toys", "Aquarium", "Reptile"]),
        "website": "petsuppliesdropship.com",
        "min_order_usd": 0,
        "shipping_days_usa": 3,
        "shipping_days_intl": 12,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": True,
        "description": "Dedicated pet dropshipping platform. 50,000+ pet products, automated fulfillment for Shopify/WooCommerce, private label options.",
        "rating": 4.4,
    },
    # ── Health, Beauty & Wellness ─────────────────────────────────────────────
    {
        "name": "McKesson Medical-Surgical",
        "country": "USA",
        "region": "USA",
        "platform_type": "distributor",
        "categories": json.dumps(["Medical Supplies", "Health", "Wellness", "OTC Medications", "First Aid"]),
        "website": "mckesson.com",
        "min_order_usd": 500,
        "shipping_days_usa": 2,
        "shipping_days_intl": 0,
        "has_usa_warehouse": True,
        "dropship_ready": False,
        "api_integration": True,
        "description": "USA's largest healthcare distributor. Medical supplies, OTC health products, wellness items for online health retailers.",
        "rating": 4.5,
    },
    {
        "name": "Beauty Joint",
        "country": "USA",
        "region": "USA",
        "platform_type": "wholesaler",
        "categories": json.dumps(["Beauty", "Makeup", "Skincare", "Hair Care", "Nail Care", "Cosmetics"]),
        "website": "beautyjoint.com",
        "min_order_usd": 50,
        "shipping_days_usa": 3,
        "shipping_days_intl": 12,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": False,
        "description": "USA beauty & cosmetics wholesaler. 500+ brands, no minimum on many items, ships same day from NJ warehouse.",
        "rating": 4.4,
    },
    # ── Food & Grocery ────────────────────────────────────────────────────────
    {
        "name": "Sysco Wholesale",
        "country": "USA",
        "region": "USA",
        "platform_type": "distributor",
        "categories": json.dumps(["Food", "Grocery", "Restaurant Supplies", "Specialty Food", "Organic Food", "Beverages"]),
        "website": "sysco.com",
        "min_order_usd": 500,
        "shipping_days_usa": 2,
        "shipping_days_intl": 0,
        "has_usa_warehouse": True,
        "dropship_ready": False,
        "api_integration": True,
        "description": "World's largest food distributor. 400,000+ products, specialty and organic food, restaurant & retail wholesale USA-wide.",
        "rating": 4.5,
    },
    {
        "name": "KeHE Distributors",
        "country": "USA",
        "region": "USA",
        "platform_type": "distributor",
        "categories": json.dumps(["Natural Food", "Organic Food", "Specialty Food", "Health Food", "Grocery", "Snacks"]),
        "website": "kehe.com",
        "min_order_usd": 300,
        "shipping_days_usa": 3,
        "shipping_days_intl": 0,
        "has_usa_warehouse": True,
        "dropship_ready": False,
        "api_integration": True,
        "description": "USA specialty & natural food distributor. 75,000+ organic, natural, specialty SKUs. Serves Whole Foods, Target, Amazon Fresh.",
        "rating": 4.4,
    },
    # ── Electronics & Tech ────────────────────────────────────────────────────
    {
        "name": "B&H Photo Video",
        "country": "USA",
        "region": "USA",
        "platform_type": "wholesaler",
        "categories": json.dumps(["Electronics", "Cameras", "Photography", "Audio", "Video", "Computers"]),
        "website": "bhphotovideo.com/c/buy/wholesale",
        "min_order_usd": 0,
        "shipping_days_usa": 2,
        "shipping_days_intl": 10,
        "has_usa_warehouse": True,
        "dropship_ready": True,
        "api_integration": True,
        "description": "NYC-based electronics & photo wholesale. Pro gear reseller program. Ships from NYC same/next day.",
        "rating": 4.7,
    },
]


def seed_dropship_directory(db) -> int:
    """Upsert seed data — always inserts entries missing by name. Safe to call on every startup."""
    existing_names = {r[0] for r in db.query(DropshipDirectory.name).all()}
    count = 0
    for item in SEED_DATA:
        if item["name"] not in existing_names:
            db.add(DropshipDirectory(**item))
            count += 1
    if count:
        db.commit()
    return count
